### ISSUE TITLE
requiring hapi module

### ISSUE THREAD

**Issue by wouldgo** [diasdavid/webrtc-explorer-signalling-server#1]
Hi @diasdavid,

coming to your repo since I'm interested in webrtc distribuited communication and I realize that you done a lot of stuff! Thanks a lot
Afterwards there's a something wrong with the `hapi` module name: seems that the require [here](https://github.com/diasdavid/webrtc-explorer-signalling-server/blob/master/src/index.js#L1) is without capital letter.

**Comment by diasdavid** [comment]
Cool, thank you @wouldgo. I believe that I never noticed because Mac OS / Linux is not case sensitive, good catch!

**Comment by wouldgo** [comment]
No problem.

Anyway my os is Debian (in fact, as far as I know, Linux is case sensitive). 
I'm going to mess around on webrtc-explorer as soon I'll I time. 

Thanks to you.

**Comment by Geremia** [comment]
I'm on Linux, too, and I needed to add `'use strict';` at the top to make it work.
